# Default initial positions for baxter's ros2_control fake system

initial_positions:
  left_e0: 0
  left_e1: 2.35619
  left_s0: 0.785398
  left_s1: -1.5708
  left_w0: 0
  left_w1: 0.785398
  left_w2: 0
  right_e0: 0
  right_e1: 2.35619
  right_s0: -0.785398
  right_s1: -1.5708
  right_w0: 0
  right_w1: 0.785398
  right_w2: 0
