# Default initial positions for baxter's ros2_control fake system

initial_positions:
  left_e0: 0
  left_e1: 1.57
  left_s0: 0.52
  left_s1: -0.55
  left_w0: 0
  left_w1: 1.26
  left_w2: 0
  right_e0: 0
  right_e1: 1.57
  right_s0: -0.52
  right_s1: -0.55
  right_w0: 0
  right_w1: 1.26
  right_w2: 0
